### ISSUE TITLE
Get a pandoc error when building

### ISSUE THREAD

**Issue by DanGoldwater1** [AngryMane/mkdocs-glossary-plugin#25]
I'm hitting an error when I try to run this plugin. This is on a codespace, so should be a clean environment. I've tried a couple of fresh installs and still get the error. Without the plugin, mkdocs works fine on this project. I've also double checked that pandoc is installed correctly. 

Here's the error:

```
 python -m mkdocs serve
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pandoc/__init__.py", line 87, in configure
    pandoc = plumbum.local["pandoc"]
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/plumbum/machines/local.py", line 242, in __getitem__
    return LocalCommand(self.which(cmd))
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/plumbum/machines/local.py", line 202, in which
    raise CommandNotFound(progname, list(cls.env.path))
plumbum.commands.processes.CommandNotFound: (CommandNotFound(...), 'pandoc', [<LocalPath /usr/local/rvm/gems/ruby-3.1.3/bin>, <LocalPath /usr/local/rvm/gems/ruby-3.1.3@global/bin>, <LocalPath /usr/local/rvm/rubies/ruby-3.1.3/bin>, <LocalPath /vscode/bin/linux-x64/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/remote-cli>, <LocalPath /home/codespace/.local/bin>, <LocalPath /home/codespace/.dotnet>, <LocalPath /home/codespace/nvm/current/bin>, <LocalPath /home/codespace/.php/current/bin>, <LocalPath /home/codespace/.python/current/bin>, <LocalPath /home/codespace/java/current/bin>, <LocalPath /home/codespace/.ruby/current/bin>, <LocalPath /home/codespace/.local/bin>, <LocalPath /usr/local/oryx>, <LocalPath /usr/local/go/bin>, <LocalPath /go/bin>, <LocalPath /usr/local/sdkman/bin>, <LocalPath /usr/local/sdkman/candidates/java/current/bin>, <LocalPath /usr/local/sdkman/candidates/gradle/current/bin>, <LocalPath /usr/local/sdkman/candidates/maven/current/bin>, <LocalPath /usr/local/sdkman/candidates/ant/current/bin>, <LocalPath /usr/local/rvm/gems/default/bin>, <LocalPath /usr/local/rvm/gems/default@global/bin>, <LocalPath /usr/local/rvm/rubies/default/bin>, <LocalPath /usr/local/share/rbenv/bin>, <LocalPath /opt/conda/bin>, <LocalPath /usr/local/php/current/bin>, <LocalPath /usr/local/python/current/bin>, <LocalPath /usr/local/py-utils/bin>, <LocalPath /usr/local/nvs>, <LocalPath /usr/local/share/nvm/versions/node/v19.7.0/bin>, <LocalPath /usr/local/hugo/bin>, <LocalPath /usr/local/dotnet/current>, <LocalPath /usr/local/sbin>, <LocalPath /usr/local/bin>, <LocalPath /usr/sbin>, <LocalPath /usr/bin>, <LocalPath /sbin>, <LocalPath /bin>, <LocalPath /home/codespace/.dotnet/tools>, <LocalPath /usr/local/rvm/bin>])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/python/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 301, in <module>
    cli()
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/codespace/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 78, in serve
    config = get_config()
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/base.py", line 363, in load_config
    errors, warnings = cfg.validate()
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/base.py", line 228, in validate
    run_failed, run_warnings = self._validate()
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/base.py", line 186, in _validate
    self[key] = config_option.validate(value)
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 147, in validate
    return self.run_validation(value)
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 939, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 975, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/home/codespace/.local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 993, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/usr/local/python/3.10.4/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/python/3.10.4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs_glossary_plugin/plugin.py", line 18, in <module>
    from pandoc.types import *
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pandoc/types.py", line 184, in <module>
    pandoc.configure(auto=True)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/pandoc/__init__.py", line 93, in configure
    raise RuntimeError(message)
RuntimeError: cannot find the pandoc program.
paths:['/usr/local/rvm/gems/ruby-3.1.3/bin', '/usr/local/rvm/gems/ruby-3.1.3@global/bin', '/usr/local/rvm/rubies/ruby-3.1.3/bin', '/vscode/bin/linux-x64/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/remote-cli', '/home/codespace/.local/bin', '/home/codespace/.dotnet', '/home/codespace/nvm/current/bin', '/home/codespace/.php/current/bin', '/home/codespace/.python/current/bin', '/home/codespace/java/current/bin', '/home/codespace/.ruby/current/bin', '/home/codespace/.local/bin', '/usr/local/oryx', '/usr/local/go/bin', '/go/bin', '/usr/local/sdkman/bin', '/usr/local/sdkman/candidates/java/current/bin', '/usr/local/sdkman/candidates/gradle/current/bin', '/usr/local/sdkman/candidates/maven/current/bin', '/usr/local/sdkman/candidates/ant/current/bin', '/usr/local/rvm/gems/default/bin', '/usr/local/rvm/gems/default@global/bin', '/usr/local/rvm/rubies/default/bin', '/usr/local/share/rbenv/bin', '/opt/conda/bin', '/usr/local/php/current/bin', '/usr/local/python/current/bin', '/usr/local/py-utils/bin', '/usr/local/nvs', '/usr/local/share/nvm/versions/node/v19.7.0/bin', '/usr/local/hugo/bin', '/usr/local/dotnet/current', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/home/codespace/.dotnet/tools', '/usr/local/rvm/bin']
```

**Comment by acmnu** [comment]
There is something wrong with environment, obviously. Is any way to run ``which pandoc`` in exact environment?
